In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.svm import SVC
from sklearn.model_selection import train_test_split
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler

#IRIS 데이터 로드
iris =  sns.load_dataset('iris') 
X= iris.iloc[:,:4] #학습할데이터
y = iris.iloc[:,-1] #타겟
print(y)

0         setosa
1         setosa
2         setosa
3         setosa
4         setosa
5         setosa
6         setosa
7         setosa
8         setosa
9         setosa
10        setosa
11        setosa
12        setosa
13        setosa
14        setosa
15        setosa
16        setosa
17        setosa
18        setosa
19        setosa
20        setosa
21        setosa
22        setosa
23        setosa
24        setosa
25        setosa
26        setosa
27        setosa
28        setosa
29        setosa
         ...    
120    virginica
121    virginica
122    virginica
123    virginica
124    virginica
125    virginica
126    virginica
127    virginica
128    virginica
129    virginica
130    virginica
131    virginica
132    virginica
133    virginica
134    virginica
135    virginica
136    virginica
137    virginica
138    virginica
139    virginica
140    virginica
141    virginica
142    virginica
143    virginica
144    virginica
145    virginica
146    virginica
147    virgini

In [2]:
scal = StandardScaler() #scaling
X = scal.fit_transform(X)

In [3]:
print(y)

0         setosa
1         setosa
2         setosa
3         setosa
4         setosa
5         setosa
6         setosa
7         setosa
8         setosa
9         setosa
10        setosa
11        setosa
12        setosa
13        setosa
14        setosa
15        setosa
16        setosa
17        setosa
18        setosa
19        setosa
20        setosa
21        setosa
22        setosa
23        setosa
24        setosa
25        setosa
26        setosa
27        setosa
28        setosa
29        setosa
         ...    
120    virginica
121    virginica
122    virginica
123    virginica
124    virginica
125    virginica
126    virginica
127    virginica
128    virginica
129    virginica
130    virginica
131    virginica
132    virginica
133    virginica
134    virginica
135    virginica
136    virginica
137    virginica
138    virginica
139    virginica
140    virginica
141    virginica
142    virginica
143    virginica
144    virginica
145    virginica
146    virginica
147    virgini

In [4]:
# One Versus Rest 구현을 위해 class가 0인것과 아닌것을 구분하기위한 machine class가 1인것과 아닌 것을 구분하기 위한 머신 등을 미리만들어줌
svm_1 = SVC(kernel ='rbf', C = 5, gamma = 5)   # rbf : 가우시안 커널을 사용한다.
svm_2 = SVC(kernel ='rbf', C = 5, gamma = 5)
svm_3 = SVC(kernel ='rbf', C = 5, gamma = 5)

In [5]:
from sklearn.model_selection import train_test_split #테스트/트레인 데이터로 분리
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=48)

In [6]:
y_train = pd.get_dummies(y_train) #one hot encoding을 먼저해보자

In [7]:
svm_1.fit(X_train,y_train.iloc[:,0]) # 데이터 클레스가 0인 애인지 아닌지 구분해주는 머신
svm_2.fit(X_train,y_train.iloc[:,1]) # 데이터 클레스가 1인 애인지 아닌지 구분해주는 머신
svm_3.fit(X_train,y_train.iloc[:,2]) # 데이터 클레스가 2인 애인지 아닌지 구분해주는 머신
print(svm_1.predict(X_test)) #데이터 클래스가 0인지 아닌지 구분해주는 애를 통해서 테스트데이터의 클래스가 0인지 0이 아닌인지 예측해보자

print(svm_1.decision_function(X_test)) #decision_function hyperplane과의 거리를 구하는 방법 필요하다면 활용해주세요

[0 0 0 0 0 0 1 0 1 0 0 1 1 0 0 0 1 0 0 0 1 0 0 0 0 1 1 0 0 0]
[-1.12470845 -0.86326953 -0.65281099 -0.50248821 -0.76284323 -0.87465573
  1.07709345 -0.99281647  0.47441336 -0.99842743 -0.83989348  0.15633457
  0.32871788 -0.97965464 -0.72385083 -0.92638376  1.28322481 -0.56240455
 -0.72719892 -0.99509775  0.43166724 -0.96451557 -0.82991366 -1.03020581
 -0.75166835  1.13461335  0.39943974 -1.04194106 -0.93376548 -1.06133798]


In [8]:
print(svm_2.predict(X_test)) 

print(svm_2.decision_function(X_test))

[1 1 1 0 0 0 0 0 0 1 0 0 0 0 1 1 0 0 0 0 0 0 1 1 0 0 0 0 0 1]
[ 1.36054602  0.62859488  0.0580828  -0.36987093 -0.25686625 -0.79229874
 -1.03195247 -0.87132049 -0.77957234  0.99327762 -0.73309581 -0.64607768
 -0.71843897 -0.80882458  0.47748663  0.69953462 -1.11879121 -0.1870504
 -0.24458236 -0.99337352 -0.76149141 -0.96812018  0.11310267  1.06892719
 -0.56749692 -1.05639624 -0.74817515 -1.0537858  -0.89721836  1.17126024]


In [9]:
print(svm_3.predict(X_test)) 

print(svm_3.decision_function(X_test))

[0 0 0 0 1 1 0 1 0 0 1 0 0 1 0 0 0 0 0 1 0 1 0 0 1 0 0 1 1 0]
[-1.26277651 -0.77964936 -0.40539105 -0.13070947  0.02643314  0.57365649
 -1.04443118  0.88027844 -0.69605517 -0.99074328  0.52442024 -0.51171892
 -0.61157919  0.78148257 -0.75517707 -0.76905925 -1.16380018 -0.25333938
 -0.0251979   0.98843144 -0.67129528  0.89577306 -0.30363489 -1.03647008
  0.31622662 -1.07758405 -0.65251719  1.09632055  0.85541707 -1.11042784]


In [10]:
# 부호가 모든 같은 경우가 있는가? 요모두 동점인 경우가 생길것이다.
for i in range(len(X_test)):
    # ~. decision_function을 이용하면 해당 데이터가 하이퍼플레인으로부터 얼마나 떨어져있는 지 거리가 나온다 다음은 그 값의 부호를 이용해
    # 모두가 동점인 경우가 있는지 출력하는 함수 
    if (np.sign(svm_1.decision_function(X_test)[i]) == np.sign(svm_2.decision_function(X_test)[i])) and (np.sign(svm_2.decision_function(X_test)[i]) == np.sign(svm_3.decision_function(X_test)[i])):
        print(i)

3
17
18


In [13]:
## Case 1 : One vs Rest SVM을 이부분에 구현해주세요 위 결과들을 이용해서 multi class SVM을 직접 구현해주세요! 하드코딩이 하시기 편할겁니다.
predict_arr = np.ones(30)
for i in range(len(X_test)):
    max_value = max(svm_1.decision_function(X_test)[i],svm_2.decision_function(X_test)[i], svm_3.decision_function(X_test)[i])
   
    if(max_value == svm_1.decision_function(X_test)[i]) : 
        print(i,'setosa')
        predict_arr[i]=0
    elif(max_value == svm_2.decision_function(X_test)[i]):
        print(i,'versicolor')
        predict_arr[i]=1
    else:
        print(i, 'virginica')
        predict_arr[i]=2

0 versicolor
1 versicolor
2 versicolor
3 virginica
4 virginica
5 virginica
6 setosa
7 virginica
8 setosa
9 versicolor
10 virginica
11 setosa
12 setosa
13 virginica
14 versicolor
15 versicolor
16 setosa
17 versicolor
18 virginica
19 virginica
20 setosa
21 virginica
22 versicolor
23 versicolor
24 virginica
25 setosa
26 setosa
27 virginica
28 virginica
29 versicolor


In [14]:
predict_arr

array([1., 1., 1., 2., 2., 2., 0., 2., 0., 1., 2., 0., 0., 2., 1., 1., 0.,
       1., 2., 2., 0., 2., 1., 1., 2., 0., 0., 2., 2., 1.])

In [17]:
test_value = y_test.values
test_arr=np.ones(30)

for i in range(len(test_value)):
    if test_value[i]=='setosa':
        test_arr[i]=0
    elif test_value[i]=='versicolor':
        test_arr[i]=1
    else:
        test_arr[i]=2


In [18]:
test_arr

array([1., 1., 2., 0., 1., 2., 0., 2., 0., 1., 2., 0., 0., 2., 1., 1., 0.,
       1., 1., 2., 0., 2., 1., 1., 2., 0., 0., 2., 2., 1.])

In [20]:
from sklearn.metrics import accuracy_score

accuracy_score(test_arr,predict_arr)

0.8666666666666667

In [ ]:
# Case 2 : One vs One SVM을 이 부분에 구현해주세요. 이것은 선택사항입니다! 

In [19]:
# 그냥 원래 라이브러리가 제공하는 멀티클래스 SVM과 여러분이 구현한 multiclass SVM결과를 한 번 비교해주세요
from sklearn.metrics import accuracy_score
from sklearn.model_selection import train_test_split #데이터셋 분리
X_train_2, X_test_2, y_train_2, y_test_2 = train_test_split(X, y, test_size=0.2, random_state=48)

svm_4 = SVC(kernel ='rbf', C = 5, gamma = 5)
svm_4.fit(X_train_2, y_train_2)
y_pred = svm_4.predict(X_test_2)

accuracy_score(y_test_2,y_pred)

0.8333333333333334